### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str' when running seqtk_parser.py

### ISSUE THREAD

**Issue by bsalehe** [cambiotraining/bacterial-genomics#16]
I have been getting this error since yesterday when I was running that script for S_pneumoniae. I wonder if this is the bug or wrong inputs?? The command I write is:
`python scripts/seqtk_parser.py -i results/bactmap/pseudogenomes_check`. I get the following error:

> Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Course_Materials/S_pneumoniae/scripts/seqtk_parser.py", line 63, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/Course_Materials/S_pneumoniae/scripts/seqtk_parser.py", line 57, in main
    seqtk_df = seqtk_to_dataframe(seqtk_files)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Course_Materials/S_pneumoniae/scripts/seqtk_parser.py", line 41, in seqtk_to_dataframe
    seqtk_df["%ref mapped"] = seqtk_df['mapped'] / seqtk_df['ref_length'] * 100
                              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/arraylike.py", line 210, in __truediv__
    return self._arith_method(other, operator.truediv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/series.py", line 5815, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/base.py", line 1381, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 229, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 165, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'str'

Any thoughts on this??

Thanks

**Comment by tavareshugo** [comment]
Can you specify the exercise and section?

**Comment by avantonder** [comment]
I think this is related to the name of the bash script being wrong - should be `02-pseudogenome_check.sh` (section 26). If you activate the seqtk environment then run this script which includes `scripts/seqtk_parser.py` it should work (just tested it)

**Comment by tavareshugo** [comment]
Yes, I've realised this as I was checking, opened #17

**Comment by bsalehe** [comment]
I activated seqtk env then just ran `bash scripts/02-pseudogenome_check.sh` I get the same error. See below:

> Processing ERX1265396_ERR1192012.fas
Processing ERX1265488_ERR1192104.fas
Processing ERX1501202_ERR1430824.fas
Processing ERX1501203_ERR1430825.fas
Processing ERX1501204_ERR1430826.fas
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'str'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/Course_Materials/S_pneumoniae/scripts/seqtk_parser.py", line 63, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/Course_Materials/S_pneumoniae/scripts/seqtk_parser.py", line 57, in main
    seqtk_df = seqtk_to_dataframe(seqtk_files)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Course_Materials/S_pneumoniae/scripts/seqtk_parser.py", line 41, in seqtk_to_dataframe
    seqtk_df["%ref mapped"] = seqtk_df['mapped'] / seqtk_df['ref_length'] * 100
                              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/arraylike.py", line 210, in __truediv__
    return self._arith_method(other, operator.truediv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/series.py", line 5815, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/base.py", line 1381, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 229, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/seqtk/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 165, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'str'


Cheers!

**Comment by avantonder** [comment]
Is this still the original version of the script or does it include the fix implemented in Issue #4

**Comment by bsalehe** [comment]
The script looks as it is below:

```
#!/bin/bash

#### Settings #####

# directory with pseudogenome FASTA

fasta_dir="results/bactmap/pseudogenomes"

# output directory for results
outdir="results/bactmap/pseudogenomes_check"

# path to seqtk_parser.py
parser="scripts/seqtk_parser.py"

#### End of settings ####


#### Analysis ####
# WARNING: be careful changing the code below

# exit upon any error
set -e

# create output directory
mkdir -p $outdir

# loop through each pseudogenome
for filepath in $(ls $fasta_dir/*.fas | grep -v "aligned_")
do
    # get the sample name
    sample=$(basename $filepath)

    # print a message
    echo "Processing $sample"

    # run seqtk command
    seqtk comp $filepath > ${outdir}/${sample}.tsv
done

# run seqtk_parser.py
python $parser --input_dir $outdir

# move mapping_summary.tsv to results/bactmap/pseudogenomes_check
mv mapping_summary.tsv $outdir
```
The only difference I think is in the "aligned_" in the for loop which based on the issue #4 should be "aligned_genomes". Not sure the missing word "genomes" causes error or something else.

Cheers!

**Comment by bsalehe** [comment]
I added "genomes" but keep getting the same error

**Comment by avantonder** [comment]
Can you check that there isn't already a `mapping_summary.tsv` file in the `pseudogenomes_check` directory from your previous attempt to run the script. If there is, delete and try again. I've just copied  the `pseudogenomes` directory from preprocessed to `results/bactmap` and ran the updated version of the script and it worked

**Comment by tavareshugo** [comment]
That's the issue @avantonder we just realised. OK, we need to be careful during the course.

**Comment by tavareshugo** [comment]
could we remove the individual TSV files in the bash script? Or are they used for anything else?

**Comment by tavareshugo** [comment]
sorry, that wouldn't solve the problem. 
Maybe we can create a temporary directory where the `seqtk comp` files are output and then remove that directory

**Comment by avantonder** [comment]
The seqtk comp outputs are saved to the pseudogenomes_check directory already. They're not the problem, the presence of a TSV file in a different format is. The problem should only arise if the script fails for some reason and is then run again when the mapping_summary.tsv file has been created. Assuming the participants follow the instructions and run the bash script as it is there shouldn't be a problem
